# ADDING A NEW MACHINE:
# create key
# age-keygen -o ~/.config/sops/age/keys.txt

# get public key
# age-keygen -y ~/.config/sops/age/keys.txt

# rekey
# sops updatekeys secrets/secrets.yaml

keys:
  - &santi_pgp 644EFF248A9CA2D269C30A7A6AA809E3B3CCCA64
  - &santi_age age1lmhxry5p45qz2m3lstvvhepdcjrf884kculesvgy7phvm4pnnsqqs63vfz
  - &machine_paranix age1rtaw7ym3j9h4wreh0r5k4rwwfk04mq0k8uml02el4xzc6u9gzyxsmdxf4n
  - &machine_devbox age1aaeur3g359p2j73c6cvemp0hy2lpdaty4rzejk3eadls9xu4k49sqje7p3
  - &machine_santiserver age1wmscunfntut4fzem9zj0dxx4wpd2farrsj6qheuwg3mzlmep5ewq4fmejw
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *santi_pgp
      age:
      - *santi_age
      - *machine_paranix
      - *machine_devbox
      - *machine_santiserver
