# ADDING A NEW MACHINE:
# create key
# age-keygen -o ~/.config/sops/age/keys.txt

# get public key
# age-keygen -y ~/.config/sops/age/keys.txt

# rekey
# sops updatekeys secrets/secrets.yaml

keys:
  - &santi_pgp 644EFF248A9CA2D269C30A7A6AA809E3B3CCCA64
  - &santi_age age1lmhxry5p45qz2m3lstvvhepdcjrf884kculesvgy7phvm4pnnsqqs63vfz
  - &machine_santisasahi age1nvasjetqhc040jhaqy88wjj8c0js8n9zcj78gme95h7mwm77842s7yd636
  - &machine_paranix age1rtaw7ym3j9h4wreh0r5k4rwwfk04mq0k8uml02el4xzc6u9gzyxsmdxf4n
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *santi_pgp
      age:
      - *santi_age
      - *machine_santisasahi
      - *machine_paranix
