# ADDING A NEW MACHINE:
# create key
# age-keygen -o ~/.config/sops/age/keys.txt

# get public key
# age-keygen -y ~/.config/sops/age/keys.txt

# rekey
# sops updatekeys secrets/secrets.yaml

keys:
  - &santi_pgp 644EFF248A9CA2D269C30A7A6AA809E3B3CCCA64
  - &santi_age age1lmhxry5p45qz2m3lstvvhepdcjrf884kculesvgy7phvm4pnnsqqs63vfz
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - pgp:
      - *santi_pgp
      age:
      - *santi_age