keys:
  - &santi age1lmhxry5p45qz2m3lstvvhepdcjrf884kculesvgy7phvm4pnnsqqs63vfz
  - &lime age1h62gf63yxpmvggkamrldutknsh2eqt365fmx4v486sv678z6f9pqm0xp5l
  - &opal age1mv34n5m248rv9r0tpkg7c35anathtp3r7ppvrj823drgnhv4ud0sz65stq
  - &jade age1qqcc655mawc6p7u4d6aeuf092ueq0dhaqmhvazkenh6at664cgxqus96nv
creation_rules:
  - path_regex: ^secrets/ntfy\.yaml$
    key_groups:
      - age:
          - *santi
          - *lime
          - *opal
          - *jade
  - path_regex: ^secrets/lime\.yaml$
    key_groups:
      - age:
          - *santi
          - *lime
  - path_regex: ^secrets/opal\.yaml$
    key_groups:
      - age:
          - *santi
          - *opal
